### ISSUE TITLE
Global TODO list

### ISSUE THREAD

**Issue by aegitarturbotelka69** [aegitarturbotelka69/aeTimmy_SoulsLike_Unity3D#3]
- [ ]  Player physics
- [ ]  Change hero \
To this: https://assetstore.unity.com/packages/3d/characters/humanoids/humans/knightess-stylized-pbr-character-212387
- [ ] Buy enemies models
- [ ] Enemy logic:
    - [ ] State machine
    - [ ] Animations
    - [ ] Stats
- [ ] Enviroment:
    - [ ] Chests
    - [ ] Torches
    - [ ] Breakable enviroment
- [ ] Player stats:
    - [ ] Level progression
- [ ] Player equipment
- [ ] Post-processing
- [ ] Techno-demo

**Comment by aegitarturbotelka69** [comment]
- [ ] Enemy attack state
- [ ] Player attack animation&state
- [ ] enemy/player stats
- [ ] hit detection enemy/player
- [ ] player hit reaction animation
- [ ] player/enemy death animation&logic
